### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by davidhearnsmith** [mlej8/InstagramBot#1]
Say I want to login to an account, go to a specific profile then follow that account? How do I do that, looked around couldn't work it out. Also i think IG now tracks mouse movements so can differentiate between a user and a bot.

**Comment by mlej8** [comment]
Hi, 

I created quickstart examples in the Scripts/ folder. The search.py in Script/ is exactly what you are looking for. Simply use you're Instagram username and password, and put the profil you'd like to follow at "Specify Instagram Profile Here". Please note that you need to download a ChromeDriver that is compatible with your browser and put it in the Script/ folder.

Thanks,

Michael

**Comment by davidhearnsmith** [comment]
Got it thanks!

**Comment by davidhearnsmith** [comment]
Does it support proxies?

**Comment by davidhearnsmith** [comment]
For example;

https://stackoverflow.com/questions/17082425/running-selenium-webdriver-with-a-proxy-in-python

**Comment by mlej8** [comment]
Will be implemented soon ! I just updated using webdriver_manager so you no longer have to download the executables, simply run the examples scripts.

**Comment by davidhearnsmith** [comment]
Am also interested in mouse movements, that way it looks to Instagram that there is a real person controlling rather than a bot, they have just implemented a load of follow and unfollow blocks for bots. Jarvee a big bot provider is barely functional anymore.

**Comment by mlej8** [comment]
Yes, ActionChains can be used instead of WebElement.click() to simulate mouse interactions.

**Comment by davidhearnsmith** [comment]
Is this something that can be easily implemented?

**Comment by mlej8** [comment]
Yes, see https://seleniumhq.github.io/selenium/docs/api/py/webdriver/selenium.webdriver.common.action_chains.html

However, I found that using WebElement.click() was more consistent and did not gave me StaleElementExceptions as opposed to ActionChains.

**Comment by davidhearnsmith** [comment]
Can it just move the mouse to the button, that's all it needs to do 👍

**Comment by davidhearnsmith** [comment]
You can barely follow our unfollow or like with bots anymore as Instagram
can detect mouse movements.
